### ISSUE TITLE
CSS3选择器使用技巧

### ISSUE THREAD

**Issue by flyingliu** [flyingliu/github#13]
# 使用:not 来简化样式代码

### 用:not排除列表中最后一个li.
``` css
.posts {
  list-style: none;
  width:400px;
  margin: 0;
  padding: 20px;
  margin: 4rem auto;
  background: #f00;
}
.posts li:not(:last-of-type){
  border-bottom: 1px solid #000;
  margin-bottom: .5rem;
  padding-bottom: .5rem;
}
```

### 排除倍数

``` sass
ul {
    font-size: 0;
    border: 1px solid red;
    padding: 0;
    margin: 0;
    li {
        font: 14px/2 arial;
        width: calc(25% - 9px);
        border: 1px solid #ccc;
        display: inline-block;
        margin-right:12px;
        box-sizing: border-box;
        &:nth-child(4n) { margin-right:0;}
        &:not(:nth-child(4n)) { background: #eee;}
    }
}

```
